name: Stanley International
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43673
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F273C'
    - '#608468'
    - '#DAD6D3'
    - '#525357'
    - '#892237'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
