layout_spectrum: 0.1776936
typography_spectrum: 0.8678002
color:
  saturation: 0.01140475
  lightness: 0.9815592
  brandStrength: 0.6269979
  rhythmicContrast: 0.5352852
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Stanley International
