collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.01140475
  brandStrength: 0.9489796
  lightness: 0.9815592
  brandColors:
    - '#1F273C'
    - '#608468'
    - '#DAD6D3'
    - '#525357'
    - '#892237'
  rhythmicContrast: 0.5352852
typography_spectrum: 0.8678002
layout_spectrum: 0.1776936
name: Stanley International
